In [3]:
#Day2- Python-Algebra

import numpy as np

rng = np.random.default_rng()

#create Random numbers

A = rng.integers(1,10,(3,3))
b = rng.integers(1,10,(3,1))


#Print the vectors A and b

In [6]:
A,b

(array([[3, 4, 2],
        [7, 7, 5],
        [6, 8, 4]]),
 array([[9],
        [7],
        [6]]))

#print the Transpose of A

In [7]:
A.T

array([[3, 7, 6],
       [4, 7, 8],
       [2, 5, 4]])

#Dot product or Matrix multiplication in different ways.*

In [10]:
result=np.dot(A,b)
result1= A @ b
result,result1

(array([[ 67],
        [142],
        [134]]),
 array([[ 67],
        [142],
        [134]]))


#Compute determinant, eigenvalues


In [11]:
det=np.linalg.det(A)
eigenvalues,eigenvectors=np.linalg.eig(A)
det,eigenvalues,eigenvectors

(np.float64(0.0),
 array([ 1.52462113e+01,  2.48171887e-15, -1.24621125e+00]),
 array([[-0.32879797, -0.64699664,  0.32879797],
        [-0.67783439,  0.10783277, -0.67783439],
        [-0.65759595,  0.75482941,  0.65759595]]))